spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:bucket-list    # (2) JDBC URL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: bucket-list-test-key                          # 추후 제거
    type: Bearer
    accessTokenExpirationDateInMs: 5 * 60 * 1000          # 5 min
    refreshTokenExpirationDateInMs: 24 * 60 * 60 * 1000   # 1 day