spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:bucket-list    # (2) JDBC URL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: bucket-list-test-key

  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle: 0